Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Models/ErrorViewModel.cs
using System;

namespace WebPlatform.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebPlatform.DataAccess.Services;
using WebPlatform.DataAccess.ViewModels;

namespace WebPlatform.Controllers
{
    public class EventController : Controller
    {
        private readonly EventService _eventService;

        public EventController(EventService eventService)
        {
            _eventService = eventService;
        }

        public IActionResult Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(_eventService.GetEventsForUser(Guid.Parse(userId)));
        }

        public async Task<IActionResult> Create()
        {
            return View(new NewEventViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewEventViewModel vm)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            vm.OwnerId = Guid.Parse(userId);
            _eventService.AddNewEvent(vm);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(Guid eventId)
        {
            var eventVm = _eventService.GetEventById(eventId);
            var eventCategories = _eventService.GetCategoriesForEvent(eventId);
            var vm = new EventDetailsViewModel {EventDetails = eventVm, TicketCategories = eventCategories};
            
            return View(vm);
        }
    }
}

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebPlatform.Models;

namespace WebPlatform.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebPlatform.DataAccess;
using WebPlatform.DataAccess.Services;
using WebPlatform.DataAccess.ViewModels;

namespace WebPlatform.Controllers
{
    public class TicketsController : Controller
    {
        private readonly TicketService _ticketService;
        private readonly TransferService _transferService;
        private readonly IConfiguration _configuration;

        public TicketsController(TicketService ticketService, TransferService transferService, IConfiguration configuration)
        {
            _ticketService = ticketService;
            _transferService = transferService;
            _configuration = configuration;
        }

        public IActionResult Index(Guid eventId)
        {
            return View();
        }

        public async Task<IActionResult> CreateTicketCategory(Guid eventId)
        {
            return View(new NewTicketCategoryViewModel{EventId = eventId});
        }

        [HttpPost]
        public async Task<IActionResult> CreateTicketCategory(NewTicketCategoryViewModel vm)
        {
            _ticketService.AddTicketCategory(vm);
            return RedirectToAction("Details", "Event", new {eventId = vm.EventId});
        }

        public async Task<IActionResult> ShowTicketsForEvent(Guid categoryId)
        {
            var vm =_ticketService.GetTicketsForTicketCategory(categoryId);
            return View(vm);
        }

        public async Task<IActionResult> TransferTicket(string ticketId)
        {
            var vm = new TransferTicketViewModel {TicketId = ticketId};
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> TransferTicket(TransferTicketViewModel vm)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            _transferService.Transfer(vm.TicketId, Guid.Parse(userId), vm.ReceiverEMail);
            return RedirectToAction("Index");
        }
    }
}

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Event/Create.cshtml
@model WebPlatform.DataAccess.ViewModels.NewEventViewModel
<h2>My Events</h2>

<form asp-controller="Event" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="EventDateTime" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="EventDateTime" type="date" class="form-control" />
            <span asp-validation-for="EventDateTime" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="EventName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="EventName" class="form-control" />
            <span asp-validation-for="EventName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="SmartContractId" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="SmartContractId" class="form-control" />
            <span asp-validation-for="SmartContractId" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</form>

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Event/Details.cshtml
@model WebPlatform.DataAccess.ViewModels.EventDetailsViewModel
<h2>@Model.EventDetails.EventName</h2>

<p>@Model.EventDetails.Description</p>

<a asp-controller="Tickets" asp-action="CreateTicketCategory" asp-route-eventId="@Model.EventDetails.EventId">Create new Tickettype</a>
<h3>Tickets</h3>
@foreach (var tc in Model.TicketCategories)
{
<div class="row">
    <div class="col-md-3">@tc.Name</div>
    <div class="col-md-3">@tc.NumberOfTickets</div>
    <div class="col-md-3">@tc.Price</div>
    <div class="col-md-3"><a asp-controller="Tickets" asp-action="ShowTicketsForEvent" asp-route-categoryId="@tc.TicketCategoryId">Show Tickets</a></div>
</div>
}

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Event/Index.cshtml
@model IEnumerable<WebPlatform.DataAccess.ViewModels.EventViewModel>
<h2>My Events</h2>

<a asp-controller="Event" asp-action="Create">Create a new Event</a>

@foreach (var e in Model)
{
    <div class="row">
        <div class="col-md-3">@e.EventDateTime</div>
        <div class="col-md-3">@e.EventName</div>
        <div class="col-md-3"><a asp-controller="Event" asp-action="Details" asp-route-eventId="@e.EventId">Details</a></div>
    </div>
}

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebPlatform</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebPlatform</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Event" asp-action="Index">Events</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebPlatform</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Tickets/CreateTicketCategory.cshtml
@model WebPlatform.DataAccess.ViewModels.NewTicketCategoryViewModel
<h2>Create new ticketcategory and tickets</h2>
    
    <form asp-controller="Tickets" asp-action="CreateTicketCategory" method="post">

    <input type="hidden" asp-for="EventId"/>
    <div class="form-group">
        <label asp-for="Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Price" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Price" class="form-control"/>
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Currency" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Currency" class="form-control"/>
            <span asp-validation-for="Currency" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="NumberOfTickets" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="NumberOfTickets" class="form-control"/>
            <span asp-validation-for="NumberOfTickets" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default"/>
        </div>
    </div>
</form>

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Tickets/Index.cshtml
@model IEnumerable<WebPlatform.DataAccess.ViewModels.TicketViewModel>

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Tickets/ShowTicketsForEvent.cshtml
@model IEnumerable<WebPlatform.DataAccess.ViewModels.TicketViewModel>

<h2>Buy Tickets</h2>

@foreach (var ticket in Model)
{
<div class="row">
    <div class="col-md-3">@ticket.TicketId</div>
    <div class="col-md-3">
        @if (ticket.Sold)
            {
        <p>sold</p>
            }
            else
            {
        <p>for sale</p>
            }
    </div>
    <div class="col-md-3"><a asp-controller="Tickets" asp-action="TransferTicket" asp-route-ticketId="@ticket.TicketId">Transfer</a></div>
</div>
}

Hackathon/WebPlatform - deprecated (1st project)/WebPlatform/Views/Tickets/TransferTicket.cshtml
@model WebPlatform.DataAccess.ViewModels.TransferTicketViewModel
<h2>Transfer ticket</h2>

<form asp-controller="Tickets" asp-action="TransferTicket" method="post">

    <input type="hidden" asp-for="TicketId" />
    <div class="form-group">
        <label asp-for="ReceiverEMail" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="ReceiverEMail" class="form-control" />
            <span asp-validation-for="ReceiverEMail" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Transfer" class="btn btn-default" />
        </div>
    </div>
</form>