Hackathon/IdManagementPortal/IdManagementPortal/Models/ErrorViewModel.cs
using System;

namespace IdManagementPortal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hackathon/IdManagementPortal/IdManagementPortal/ViewModels/CheckPassportViewModel.cs
namespace IdManagementPortal.ViewModels
{
    public class CheckPassportViewModel
    {
        public string PassportNumber { get; set; }
    }
}

Hackathon/IdManagementPortal/IdManagementPortal/ViewModels/PersonInfoDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdManagementPortal.ViewModels
{
    public class PersonInfoDto
    {
        public string PassportNumber { get; set; }

        public string Fullname { get; set; }

        public string Address { get; set; }

        public string Citizen { get; set; }

        public string PictureDownloadUrl { get; set; }

        public string PictureHash { get; set; }
    }
}

Hackathon/IdManagementPortal/IdManagementPortal/ViewModels/RegisterPersonViewModel.cs
using Microsoft.AspNetCore.Http;

namespace IdManagementPortal.ViewModels
{
    public class RegisterPersonViewModel
    {
        public string PassportNumber { get; set; }

        public string FullName { get; set; }

        public string Address { get; set; }

        public string Citizen { get; set; }

        public IFormFile Photo { set; get; }

    }
}

Hackathon/IdManagementPortal/IdManagementPortal/Controllers/CheckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IdManagementPortal.BlockChainAccess;
using IdManagementPortal.Services;
using IdManagementPortal.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Neo.Lux.Core;

namespace IdManagementPortal.Controllers
{
    public class CheckController : Controller
    {
        private readonly PersonInfoService _personInfoService;

        public CheckController(PersonInfoService personInfoService)
        {
            _personInfoService = personInfoService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Check(CheckPassportViewModel vm)
        {
            var personInfo = _personInfoService.GetPersonInfo(vm.PassportNumber);
            return View(personInfo);
        }
    }
}

Hackathon/IdManagementPortal/IdManagementPortal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IdManagementPortal.Models;

namespace IdManagementPortal.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hackathon/IdManagementPortal/IdManagementPortal/Controllers/PersonInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Threading.Tasks;
using IdManagementPortal.BlockChainAccess;
using IdManagementPortal.Services;
using IdManagementPortal.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Neo.Lux.Core;

namespace IdManagementPortal.Controllers
{
    public class PersonInfoController : Controller
    {
        private readonly PersonInfoService _personInfoService;

        public PersonInfoController(PersonInfoService personInfoService)
        {
            _personInfoService = personInfoService;
        }

        [HttpGet]
        public async Task<IActionResult> GetInfo(string passportNumber)
        {
            var personInfo = _personInfoService.GetPersonInfo(passportNumber);

            return Json(personInfo);
        }
    }
}

Hackathon/IdManagementPortal/IdManagementPortal/Controllers/PictureDownloadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace IdManagementPortal.Controllers
{
    public class PictureDownloadController : Controller
    {
        public async Task<IActionResult> Download(string filename)
        {
            if (filename == null)
                return Content("filename not present");

            var path = Path.Combine(
                @"C:\PictureStorage",
                $"{filename}.jpg");

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(path), Path.GetFileName(path));
        }

        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
            }
    }
}

Hackathon/IdManagementPortal/IdManagementPortal/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using IdManagementPortal.BlockChainAccess;
using IdManagementPortal.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Neo.Lux.Core;

namespace IdManagementPortal.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult Index()
        {
            return View(new RegisterPersonViewModel());
        }

        public async Task<IActionResult> Register(RegisterPersonViewModel vm)
        {
            var img = vm.Photo;


            if (img == null || img.Length == 0)
                return Content("file not selected");

            var path = Path.Combine(@"C:\PictureStorage",
                $"{vm.PassportNumber}.jpg");

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await img.CopyToAsync(stream);
            }

            var blockChainHelper =
                new BlockChainHelper("1dd37fba80fec4e6a6f13fd708d8dcb3b29def768017052f6c930fa1c5d90bbb",
                    "0x941d5591f6d74f0c9d129777a6bae1c385a0373b", NeoRPC.ForPrivateNet());
            img.GetHashCode().ToString();
            blockChainHelper.PostSomeStuffToAContract("save", new object[] { vm.PassportNumber, Path.GetFileName(path), img.GetHashCode().ToString(), vm.FullName, vm.Address, vm.Citizen });


            return RedirectToAction("Index");
        }
    }
}

Hackathon/IdManagementPortal/IdManagementPortal/Views/Check/Check.cshtml
@model IdManagementPortal.ViewModels.PersonInfoDto

<h2>Check result</h2>

<img src="~/PictureDownload/Download?filename=@Model.PassportNumber" width="100"/>

<div class="row">
    <div class="col-md-3">Fullname</div>
    <div class="col-md-9">@Model.Fullname</div>
</div>
<div class="row">
    <div class="col-md-3">Address</div>
    <div class="col-md-9">@Model.Address</div>
</div>
<div class="row">
    <div class="col-md-3">Citizen</div>
    <div class="col-md-9">@Model.Citizen</div>
</div>

<div class="row">
    <div class="col-md-3">PictureHash</div>
    <div class="col-md-9">@Model.PictureHash</div>
</div>

Hackathon/IdManagementPortal/IdManagementPortal/Views/Check/Index.cshtml
@model IdManagementPortal.ViewModels.CheckPassportViewModel
<h2>Check passportnumber</h2>

<form asp-controller="Check" asp-action="Check" method="post">
    <div class="form-group">
        <label asp-for="PassportNumber" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="PassportNumber" class="form-control" />
            <span asp-validation-for="PassportNumber" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Check" class="btn btn-default" />
        </div>
    </div>
</form>

Hackathon/IdManagementPortal/IdManagementPortal/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>From some guys from colombia, germany and switzerland</p>

<h3>Daniel Sanchez</h3>
<h3>David Gutierrez</h3>
<h3>Matthias Bärtschi</h3>
<h3>Jeronimo </h3>
<br/>
<br />
<br />
<div>
    <img src="~/images/neo.jpg" height="100" />&nbsp;&nbsp;&nbsp;&nbsp;<img src="~/images/swisscom.jpg" height="100" />
</div>

Hackathon/IdManagementPortal/IdManagementPortal/Views/Home/Index.cshtml
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<div style="padding-right: 50%">
    <a asp-controller="Registration" asp-action="Index"><h2><img src="~/images/register.png" height="30" />&nbsp;Register a person</h2></a>
    <a asp-controller="Check" asp-action="Index"><h2><img src="~/images/passport.jpg" height="30" />&nbsp;Check a passportnumber</h2></a>
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<div style="margin-top: 100px">
    <img src="~/images/neo.jpg" height="100" />&nbsp;&nbsp;&nbsp;&nbsp;<img src="~/images/swisscom.jpg" height="100" />
</div>

Hackathon/IdManagementPortal/IdManagementPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Unithree</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/uni.png" height="30"/></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>*@
                    <li><a asp-area="" asp-controller="Registration" asp-action="Index">Register</a></li>
                    <li><a asp-area="" asp-controller="Check" asp-action="Index">Check</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>

                </ul>
                @*<partial name="_LoginPartial" />*@
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()

    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>